name: vertex

services:
  mysql:
    image: mysql:8.0
    container_name: vertex-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: vertex_backend
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - vertex-network

  redis:
    image: redis:7
    container_name: vertex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - vertex-network

  minio:
    image: minio/minio
    container_name: vertex-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      TZ: Asia/Shanghai
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - vertex-network

volumes:
  mysql-data:
  redis-data:
  minio-data:

networks:
  vertex-network:
    driver: bridge


